### ISSUE TITLE
Missing Library Refresh Button??

### ISSUE THREAD

**Issue by Angell1993** [Dummerle/Rare#10]
I just noticed something, when you buy a new game, you need to quit Rare & Launch it again to get the updated game list..

Any change for a Refresh button??

**Comment by Dummerle** [comment]
Yes  i plan it, but I don't know how to solve it smoothly

**Comment by Angell1993** [comment]
Would a simple 'legendary list-games' not provide you with a new list or is it not that simple??

**Comment by Dummerle** [comment]
Yes, but layouts are not so flexible. That is my problem

**Comment by Angell1993** [comment]
If editing the layout is not that easy, would removing the entire list and adding a new one work??
It can some times get complicated when adding or editing items on an already populated list, so starting from scratch with a new list, sometimes work..

If I knew enough about python, I would even have tried to help out, more then just pointing out some issues..

**Comment by Dummerle** [comment]
Now it works :). Now it is in the Master branch
