### ISSUE TITLE
1.5.0 does not install using pip unless specified.

### ISSUE THREAD

**Issue by Meganium97** [Dummerle/Rare#100]
I've had the problem where using pip install Rare does not install 1.5.0 but using pip install Rare==1.5.0 does. This might be of your interests.

**Comment by Dummerle** [comment]
If rare is already installed, pip will reinstall installed version. You need to add --upgrade argument or specify version

**Comment by Meganium97** [comment]
Ah, sorry. Pip was just having a little glitch installing it anew. Thank you for your help.
