### ISSUE TITLE
[CRASH] AttributeError: 'SyncWidget' object has no attribute 'download_button'

### ISSUE THREAD

**Issue by Trokinos** [Dummerle/Rare#107]
**Describe the bug**
Window 10
I had a couple of games (that i had previously uninstalled but wanted to play them again) on the Downloads , 1 was waiting of course.
I was working somewhere else and when i returned i noticed at some point Rare had certainly crashed as the Rare window wasn't there anymore, it seems one of the game was downloaded (as i see it in the legendary folder but unsure if it is complete) and the other did not .
Relaunched Rare from the command prompt (the python version as  i used pip to install and upgrade it to last version) and after loading it always crashes after a couple of seconds on the main menu.

I tried a
pip uninstall Rare
followed by a 
pip install Rare

but Rare still always crash now.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version : latest version obtained with pip install Rare  --upgrade
 - Python version

**Error message**
Traceback (most recent call last):
  File "c:\python\python39\lib\site-packages\rare\components\tabs\cloud_saves\__init__.py", line 46, in <lambda>
    self.start_thread.signal.connect(lambda x: self.setup_ui(x, app_name, auto))
  File "c:\python\python39\lib\site-packages\rare\components\tabs\cloud_saves\__init__.py", line 84, in setup_ui
    sync_widget = SyncWidget(igame, latest_save[igame.app_name], self.core)
  File "c:\python\python39\lib\site-packages\rare\components\tabs\cloud_saves\sync_widget.py", line 135, in __init__
    self.download_button.setObjectName("success")
AttributeError: 'SyncWidget' object has no attribute 'download_button'

**Comment by Dummerle** [comment]
This bug is fixed in this commit. I have to fix some errors and other bugs, then i will publish a nee release https://github.com/Dummerle/Rare/commit/18570511c45e0b5797ea6f9ec7da03c96bca2c4f
