### ISSUE TITLE
Proton issue with config through Rare

### ISSUE THREAD

**Issue by Angell1993** [Dummerle/Rare#11]
How it should be written:
[default.env]
STEAM_COMPAT_DATA_PATH = /home/angel/.local/share/wineprefixes/Proton3

How it is written:
[default.env]
steam_compat_data_path = /home/angel/.local/share/wineprefixes/Proton3

This environment variable only works in uppercase..

**Comment by Dummerle** [comment]
Configparser needs an extra option to save as uppercase. I fixed it
