### ISSUE TITLE
[BUG] Still Crashes when attempting to make desktop link

### ISSUE THREAD

**Issue by JohnGhostly** [Dummerle/Rare#123]
Attempting to create a desktop shortcut causes a crash in version 1.6.2

**To Reproduce**
Open Rare GUI
Go to the games tab
Right click on any game and select "Create desktop link"

Expected to create a desktop shortcut

 - OS: Windows 10]
 - Version 21h1
- Installation: MSI
- Python version 3.8.8
**Error message**
"[Utils] INFO: Found locale in system config: en
[Core] INFO: Trying to re-use existing login session...
[Login] INFO: You are logged in
[Utils] INFO: Found locale in system config: en"

No visible Crashlog found

**Comment by Dummerle** [comment]
You can try the latest msi file from latest commit [here](https://github.com/Dummerle/Rare/actions/runs/1389518633)

There should be a patch, which fixes it. The fix isn't in stable release yet. If it doesn't work, you see a popup with the error message

**Comment by Dummerle** [comment]
Does it work now?
