### ISSUE TITLE
[BUG] Error trying to install any game 

### ISSUE THREAD

**Issue by mrmagic223325BRRRT** [Dummerle/Rare#124]
**Describe the bug**
Whenever i click on the install game button i get a error

**To Reproduce**
1. install rare from the AUR
2. log into your account
3. try to download anything

**Desktop (please complete the following information):**
 - OS: Endeavour Linux latest version
 - Version: 1.6.9
- Installation: AUR package
- Python version: 3.9.7

**Error message**
```
[Rare] CRITICAL: Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/rare/components/main_window.py", line 51, in timer_finished
def timer_finished(self):
```
There also is this error message coming up on the screen:
```
prepare_download() got an unexpected keyword argument 'app_name'
```

**Comment by mrmagic223325BRRRT** [comment]
i managed to fix it by not using the git package from the AUR

**Comment by user4302** [comment]
please tell me how you did this.
im getting the same error when trying to update games

![image](https://user-images.githubusercontent.com/32593782/154504751-6ba13fd4-77c1-432b-a22c-4643e4d050fa.png)
