### ISSUE TITLE
[Feature Request] Support for Flatpak and Snap

### ISSUE THREAD

**Issue by dtantono** [Dummerle/Rare#134]
**Is your feature request related to a problem? Please describe.**
Flatpakl & Snapcraft is famous Linux distribution services

**Describe the solution you'd like**
I hope we can see this app on Flatpak and Snap

**Describe alternatives you've considered**
Appimage is good. But, it is good to have an alternatives. 

**Additional context**

**Comment by Dummerle** [comment]
A flatpak would be very nice. I will add it after my next changes.
Snap will have no priority, because i don't like snaps

**Comment by Dummerle** [comment]
I did some tests, but it does not work properly. App launches and you can login, but it has too less permissions, and i didn't get it to configure it right. Maybe I will try it sometimes again.

**Comment by Dummerle** [comment]
I submitted a pull request to add rare to flathub: https://github.com/flathub/flathub/pull/3001

**Comment by Dummerle** [comment]
Flatpak is ready now: https://flathub.org/apps/details/io.github.dummerle.rare
