### ISSUE TITLE
Download Progressbar

### ISSUE THREAD

**Issue by Dummerle** [Dummerle/Rare#14]
This is a very difficult issue. I don't know how to solve it

**Comment by ChemicalXandco** [comment]
I will implement this feature.

**Comment by Dummerle** [comment]
Thank you! The problem is to get the download progress. You can read it from stdout, but is not a good solution. I don't know how to interact with the Legendary API

**Comment by ChemicalXandco** [comment]
> You can read it from stdout, but is not a good solution. I don't know how to interact with the Legendary API

In order to get it directly from legendary, I will need to make changes there, but then we get the benefit of not having to parse the stdout. I have checked and the functionality required in legendary (sending the status updates to a `Queue`) is already there, it just needs to be exposed higher up.

**Comment by ChemicalXandco** [comment]
ATM I am still waiting for https://github.com/derrod/legendary/pull/235 to be merged. Also what is going on with https://github.com/Dummerle/Rare/tree/new-style? Should I target `new-style` or are you planning to rebase `new-style` into `master`?

**Comment by Dummerle** [comment]
I saw your pull request. New-style is a new version with better style and other design. You can target the version, because it will replace the current version

**Comment by ChemicalXandco** [comment]
Because my PR is still not being merged I have decided to use my fork of legendary as the dependency so I should have this feature implemented soon.

**Comment by Dummerle** [comment]
Thank you. Rodney plans to make some changes in cli and core to clean some things up. So it can take some time. For this time we can use your version
