### ISSUE TITLE
[BUG] start menu shortcut not created during installation / can't create or remove start menu link

### ISSUE THREAD

**Issue by azumukupoe** [Dummerle/Rare#143]
**Describe the bug**
start menu shortcut is not created during installation
clicking on 'Remove start menu link' gives an error

**To Reproduce**
1. Go to Settings
2. Click on 'Remove start menu link'
3. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31339007/146645333-776d1737-c46f-440a-8451-ba22ccb2811c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H2 19044.1415
- Installation: msi
- Python version: 3.10.1

**Additional context**

**Error message**
`Permission error, cannot remove C:\Users\azumu\AppData\Roaming\Microsoft\Windows\Start Menu`

**Comment by Dummerle** [comment]
I think i know, whats the error. I will push fixes for this and some other issues

**Comment by Dummerle** [comment]
The latest release should fix the error
