### ISSUE TITLE
[Feature Request]支持中文 Support for Chinese

### ISSUE THREAD

**Issue by fengguowudi** [Dummerle/Rare#146]
This is a good starter, but I think it is a little troublesome to look up the dictionary when using it. I hope to add Chinese support!

**Comment by loathingKernel** [comment]
Not something we can do ourselves, you can help translating into Chinese using the transifex service https://www.transifex.com/rare-1/rare/

**Comment by fengguowudi** [comment]
Can you add an option in simplified Chinese?

**Comment by Fancy2209** [comment]
Press the Request Language button than

**Comment by Dummerle** [comment]
I added you as translator for simplified chinese
