### ISSUE TITLE
[BUG] Crash issue in Store tab (with fix)

### ISSUE THREAD

**Issue by DavideGalilei** [Dummerle/Rare#147]
**Describe the bug**
When I go to the Store tab, Rare crashes with an error message.

**To Reproduce**
1. Go to 'Store (Beta)' tab
2. Do nothing

**Expected behavior**
Program shouldn't crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/43778739/147137724-b7f49bb0-e6e4-465d-b61f-23e05eef0eae.png)

**Desktop:**
 - OS: `Linux arch 5.15.10-arch1-1 #1 SMP PREEMPT Fri, 17 Dec 2021 11:17:37 +0000 x86_64 GNU/Linux`
 - Version: `Rare 1.8.2 Codename: Stellula Kakopo`
- Installation: AUR (https://aur.archlinux.org/packages/rare)
- Python version: `3.10.1`

**Additional context**

**Error message**
```python-traceback
[Core] INFO: Trying to re-use existing login session...
[Login] INFO: You are logged in
[Login] INFO: App starting
[Ubisoft] ERROR: No linked ubisoft account found! Link your accounts via your browser and try again.
[Rare] CRITICAL: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/rare/utils/qt_requests.py", line 75, in prepare_data
    self.request_active.handle_func(data)
  File "/usr/lib/python3.10/site-packages/rare/components/tabs/shop/shop_api_core.py", line 103, in <lambda>
    self.auth_manager.get(url, lambda data: self._handle_browse_games(data, handle_func))
  File "/usr/lib/python3.10/site-packages/rare/components/tabs/shop/shop_api_core.py", line 109, in _handle_browse_games
    handle_func(data["data"]["Catalog"]["searchStore"]["elements"])
TypeError: 'NoneType' object is not subscriptable
```

# Fix ❇️
I tried to debug the issue, and by printing data in `shop_api_core.py`, line 109, I noticed it looks like this:
```python
{'data': {'Catalog': {'searchStore': None}}, 'errors': [{'correlationId': '', 'locations': [{'column': 5, 'line': 3}], 'message': 'CatalogQuery/searchStore: Request failed with status code 400', 'path': ['Catalog', 'searchStore'], 'serviceResponse': '{"errorCode":"errors.com.epicgames.catalog.invalid_effective_date","errorMessage":"Sorry, the effective date \'[2021-12-22T07:08:51PM.677Z]\' is invalid. Valid format [yyyy-mm-dd,yyyy-mm-dd] or [yyyy-mm-ddTHH:mm:ss.SSSZ,yyyy-mm-ddTHH:mm:ss.SSSZ], e.g. [2014-10-30,2015-09-01] or [,2015-09-01] or [2014-10-30,] or [2014-10-30T01:01:01.000Z,2015-09-01T01:01:01.000Z] or [,2015-09-01T01:01:01.000Z] or [2014-10-30T01:01:01.000Z,].","messageVars":["[2021-12-22T07:08:51PM.677Z]"],"numericErrorCode":5205,"originatingService":"com.epicgames.catalog.public","intent":"prod","errorStatus":400}', 'stack': None}], 'extensions': {}}
```

As you can see, it says that the given date format is wrong. So I looked upon the code, and fixed the issue by changing a line (`shop_widget.py`, line 256) from:
```python
date = f"[,{datetime.datetime.strftime(datetime.datetime.now(), '%Y-%m-%dT%X')}.{str(random.randint(0, 999)).zfill(3)}Z]"
```
To:
```python
date = f"[{datetime.datetime.strftime(datetime.datetime.now(), '%Y-%m-%d')},]"
```

After the attemped fix, Rare seems to work fine on Store tab.

**Comment by DavideGalilei** [comment]
Pull Request: https://github.com/Dummerle/Rare/pull/148

**Comment by DavideGalilei** [comment]
Followup: I also tried to uninstall Rare and reinstall it from python sources, and it works fine without the proposed fix.

**Comment by Dummerle** [comment]
I fixed it in another way. I just added a try/except

**Comment by Dummerle** [comment]
Are there games listed in games area?

**Comment by DavideGalilei** [comment]
Sorry for the delay, I haven't received a notification about the comment.
![image](https://user-images.githubusercontent.com/43778739/147347937-ab2f35cc-6309-4af1-86e7-4a0a60faadb8.png)

As you can see, there are no games listed there, except for a single one.

**Comment by Dummerle** [comment]
Okay thank you! The request is broken
