### ISSUE TITLE
[BUG] Error When Installing Games Using Git Version

### ISSUE THREAD

**Issue by JihacK** [Dummerle/Rare#152]
**Describe the bug**
Everytime I tried to install the game the error keep appear

**To Reproduce**
1. Go to Games Tab
2. Click on Game Image
3. Click on Install Game

**Expected behavior**
Able to Install The Game

**Screenshots**
![image](https://user-images.githubusercontent.com/41344571/147406820-14e4b367-3b64-4f24-89a7-990cf55bf4fc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2
- Installation pip
- Python version 3.9.9

**Comment by MultisampledNight** [comment]
Solved on Discord, TLDR if someone stumbles this: Currently Rare has issues when legendary-gl is installed as well. Uninstall it and use one of the builds in the Actions tab, install _directly_ from source (not using the pip method to the zip archive, that doesn't contain the legendary submodule for some reason), or install using pip.
