### ISSUE TITLE
How to Link Origin Account?

### ISSUE THREAD

**Issue by cow-killer** [Dummerle/Rare#153]
I noticed since version 1.7.0 there's a way to launch Origin games. How exactly can I play Origin games through Rare?

**Comment by Dummerle** [comment]
They are listed in the game list. Origin must be installed. Then you can launch it like every other game. 
If you are on linux, you have to select correct wine prefix

**Comment by MultisampledNight** [comment]
From what I've understood, you can only forward Origin games to Origin itself through Rare which the original EGL would know of as well. For example, Star Wars Battlefront 2 has been available through the EGS, but Mirror's Edge Catalyst not (yet).

**Comment by Dummerle** [comment]
Can I close this issue?
