### ISSUE TITLE
Wine/Crossover support

### ISSUE THREAD

**Issue by CTRL-ALT-DEL-92** [Dummerle/Rare#16]
Dear Rare Developer,

The programs runs fine on wine/crossover, on both macos and linux, it just requires visual c++ 2019. The only problem is that to open  rare.exe wine or crossover must be run with root privileges, else an error appears, msvcp140.dll could not be extracted fopen permission denied. I've successfully crosscompiled it using wine python pip, it runs like a charm, I've been playing for the king with saves synced properly. My new rare.exe works for both windows and wine,without root permissions. Compiling rare with wine vanilla causes rare.exe to crash on crossover, the other way around, runs on both wine and crossover. If you don't feel to recompile rare with crossover, Can I aid you in this task? This way you'll support both linux and macos through crossover.  Thanks for your amazing Job. You Rock!!

**Comment by ChemicalXandco** [comment]
Rare is cross platform and already works on Linux, why use wine when you can run it natively?

**Comment by CTRL-ALT-DEL-92** [comment]
Hi,

Many apple M1 users weren't able to install rare using pip or pip3 install rare due to pyqtwebengine not avalible for their platform. Using rare.exe crosscompiled with crossover they were able to run your software.

**Comment by Dummerle** [comment]
There is a branch "without-browser", so you can use this, if pyqtwebengine doesn't work. 
I can't test it on a mac, because I have not a mac. I can add a note in README
