### ISSUE TITLE
Clean up the setup.py

### ISSUE THREAD

**Issue by C0D3D3V** [Dummerle/Rare#165]
Why is pywebview an optional requirement?
https://github.com/Dummerle/Rare/blob/733e784f9761ea4d585ce03504e429764e5b56a2/setup.py#L19-L24

**Comment by MultisampledNight** [comment]
That was created a few days ago in #160 in order to support logging in via a webengine running inside of Rare, making the login process easier for people who are not too well versed with JSON.

**Comment by C0D3D3V** [comment]
Ah I see, the actual dependency is legendary and that in turn imports pywebview [only if it is installed.](https://github.com/derrod/legendary/blob/d7360eef3e2ed5816da5549d71d5bce57e129df3/legendary/utils/webview_login.py#L12) Sorry for my hasty question :D I just didn't notice where webview is included, but if that happens in legendary, it's clear that I can't find anything in Rare.

**Comment by MultisampledNight** [comment]
No worries, feel free to ask as many questions as you want :D
