### ISSUE TITLE
[BUG] Ubuntu 20.04 app doesn't launch

### ISSUE THREAD

**Issue by Rushmore75** [Dummerle/Rare#167]
**Describe the bug**
I re-downloaded the latest release and now when I launch the rare I get an error message (log file uploaded)

**To Reproduce**
1. Launch rare

**Expected behavior**
Launcher launches and I would be on my merry way

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version 1.8.7
- Installation .deb
- Python version 3.8.10

**Additional context**
Had the launcher installed with an earlier version at one point

**Error message**
[Rare_22-02-14--21-25.log](https://github.com/Dummerle/Rare/files/8065789/Rare_22-02-14--21-25.log)
gs/

**Comment by Dummerle** [comment]
The bug should be fixed in https://github.com/Dummerle/Rare/commit/0bc15be1f67ec5eac944cc5e159db196375dffa6
Which is in version 1.8.7. Did you really download the latest release? Check it with `rare --version`

**Comment by Rushmore75** [comment]
it appears i thinks it is 1.8.4

**Comment by Dummerle** [comment]
I see the automatic workflow from the release failed and i build it on my pc. Maybe i did something wrong. You can download the deb file from latest commits from here: https://github.com/Dummerle/Rare/runs/5078075352?check_suite_focus=true

It might be unstable. I will update the release file later

**Comment by Rushmore75** [comment]
thanks
