### ISSUE TITLE
[Feature Request] Allow to use custom options/commands for each game in wine

### ISSUE THREAD

**Issue by neuromancer** [Dummerle/Rare#168]
**Is your feature request related to a problem? Please describe.**
Some games can work better using certain command options or wine commands. For instance, Stubbs the Zombie in Rebel Without a Pulse requires `__GL_ExtensionStringVersion=17700` to avoid heavy graphical glitches, but there is no easy to way do this in rare.

**Describe the solution you'd like**
A way to customize how each game is run using wine (extra command line, env variables, etc).

**Describe alternatives you've considered**
Steam or GameHub already have a input box for extra commands, that should be more than enough to fix this.

**Comment by loathingKernel** [comment]
That is already partially implemented by the wrapper feature. You can have a script that exports said variables and then executes the command passed to it.

**Comment by aznd** [comment]
What do you mean with those "extra command line"?
Could you maybe give me an example?
@neuromancer

**Comment by neuromancer** [comment]
It seems that the command line for calling each game was in the info section, which is is very hard to find in grid mode when using a large screen (as you will need to click exactly in the tiny `i` symbol and if you miss it, the game will run). I'm closing this issue.

**Comment by loathingKernel** [comment]
> It seems that the command line for calling each game was in the info section, which is is very hard to find in grid mode when using a large screen

Yes it is, we are working on that.

**Comment by neuromancer** [comment]
Sure, just ping me here and I can test it.

**Comment by aznd** [comment]
@neuromancer If you really need the feature, you can use it now: https://github.com/aznd/Rare/tree/envvars there are still some things missing, but base functionality is there.
