### ISSUE TITLE
[Feature Request] Make wrapper option available with proton enabled

### ISSUE THREAD

**Issue by ZhaoZuohong** [Dummerle/Rare#171]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I use some wrapper command like [MangoHUD](https://github.com/flightlessmango/MangoHud) and [OBS-VkCapture](https://github.com/nowrep/obs-vkcapture). However, when I use proton in Rare, I cannot modify wrapper option.

**Describe alternatives you've considered**
It would be nice if Rare supports these two commands, but Rare will have to check for existence of them before game launches.

**Additional context**

**Comment by Dummerle** [comment]
Update the wrapper settings is planned, but not finished yet. Mangohud settings are still in work. An alternative would be, to edit the config file at home/.config/legendary/config.ini . there you can edit wrappers manually
