### ISSUE TITLE
[BUG] Discord RPC doesn't work

### ISSUE THREAD

**Issue by headassbtw** [Dummerle/Rare#184]
**Describe the bug**
Discord rich presence does not work

**To Reproduce**
1. Launch the app
2. Go to settings
3. Toggle the discord presence settings a few times (or not at all)
4. See it not work in discord

**Expected behavior**
I expected the rich presence to work , however it's not

I've tried both the latest AppImage, and the [AUR package](https://aur.archlinux.org/packages/rare), and while the AppImage does show the status, it only updates when the app is started, and does not change or go away when i adjust the settings from within the app itself

**Screenshots**
![image](https://user-images.githubusercontent.com/16214950/156707367-2cfb1d58-698b-4b04-b237-dd39ed34daa2.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 1.8.7
- Installation: AppImage and AUR
- Python version: 3.10.2

**Additional context**

**Error message**
AUR: `[Window] WARNING: Discord RPC module not found`
AppImage: [none]

**Comment by aznd** [comment]
Do you have python-pypresence installed? The error pretty much says it all. And it works with the appimage probably because a appimage comes bundled with dependencies.

**Comment by Dummerle** [comment]
When you install it from aur, you have to install python-pypresence. It is an optional package dependency. I will check, why appimage does not work

**Comment by headassbtw** [comment]
just tested, installing python-pypresence with the aur version gives the same result as the AppImage

**Comment by Dummerle** [comment]
I fixed Discord RPC in https://github.com/Dummerle/Rare/commit/12fe9a0078c74fd8fb492301101391de448edba4

You can download the latest AppImage from [Actions](https://github.com/Dummerle/Rare/actions/runs/1959746091)
