### ISSUE TITLE
[Feature Request] Flatpaks (mainly for SteamDeck)

### ISSUE THREAD

**Issue by isopix** [Dummerle/Rare#192]
Hi,

Because SteamDeck's  root filesystem is r/o and get's overwritten every upgrade, its encouraged that everything installed outside of SteamStore be provided as FlatPaks (there's 'Discover' already in 'desktop mode' pinned to taskbar for easy installation)

I don't want Heroic, which is nearly 500MB BloatWare (in comparison to your's 5MB client)

**Comment by Dummerle** [comment]
Flatpak will be supported with the next major release. I have some test files ready, but the code needs some fixes, to support flatpak. 

I probably will create a test release, with flatpak support. Some features are planned or in progress for the next release, so it takes a little time

**Comment by Dummerle** [comment]
I submitted a pull request to add a flatpak to flathub: https://github.com/flathub/flathub/pull/3001

**Comment by Dummerle** [comment]
A flatpak is ready: https://flathub.org/apps/details/io.github.dummerle.rare
