### ISSUE TITLE
[Feature Request] Download speed limit

### ISSUE THREAD

**Issue by halfpast-learn** [Dummerle/Rare#205]
**Is your feature request related to a problem? Please describe.**
I'd like to use only part of my internet bandwidth while downloading things

**Describe the solution you'd like**
I'd like to use in-app download speed limit for this. For example, set limit to 5 MB/s and still have 5 MB/s for other things.

**Describe alternatives you've considered**
I considered limiting available bandwidth via powershell, but in windows the rules are set for .exe file, which is 'python.exe' for me, so limiting available bandwidth for Rare might also affect other python apps

**Comment by loathingKernel** [comment]
This is not supported by the backend software, legendary. You can emulate it by reducing the number of workers on a download to 1 or 2.

**Comment by halfpast-learn** [comment]
> This is not supported by the backend software, legendary

Sorry, didn't know that. Then I guess I should post a feature request there :)
