### ISSUE TITLE
[BUG] Current shared memory cache is smaller than required ?

### ISSUE THREAD

**Issue by Trokinos** [Dummerle/Rare#206]
Window 10, using the current version of Rare, i was going to download Bioshock Infinite (part of the Bioshock Collection that is free this week on the epic store) , when i ran into 
![465489](https://user-images.githubusercontent.com/14024168/170552084-0e244c19-cb09-4984-b641-a9e737a776f5.jpg)

That's very odd considering last week i could install Borderlands 3 without problem (and is a 90gb download ! way more than bioshock infinite )

**Comment by loathingKernel** [comment]
You can change the shared memory amount in the settings under the number of download worker. I will investigate if we can add a shared memory override setting directly in the install dialog.

**Comment by Dummerle** [comment]
I get the same error. As a workaround you can increase max memory in Settings -> Legendary

I will add an option to change cache size in the dialog. Maybe I will catch this error and automatically increase size.
