### ISSUE TITLE
[BUG] Rare flatpak crashes on launch after login

### ISSUE THREAD

**Issue by rederick29** [Dummerle/Rare#210]
**Describe the bug**
The rare flatpak crashes after first login and subsequently on every launch after that.

**To Reproduce**
1. Install flatpak
2. Open and login through sid from browser
3. Rare crashes with an empty window called Error briefly appearing
4. Attempting to relaunch will also crash

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: SteamOS Holo
 - Version 3.2
- Installation Flathub
- Python version System python is version 3.10.2

**Additional context**
Running on a Steam Deck

**Error message**
You can find error message in ~/.cache/rare/logs/
[Rare_22-06-18--10-22.log](https://github.com/Dummerle/Rare/files/8933307/Rare_22-06-18--10-22.log)

**Comment by Dummerle** [comment]
I never got this error before and I can't reproduce it. 

Does `/home/user/.var/app/io.github.dummerle.rare/config/legendary` exists? If yes remove metadata subdirectory and try again. 
If it still doesn't work add `disable_auto_aliasing=True` in config .ini in the above mentioned directory:
```
[Legendary]
disable_auto_aliasing=True
(.. some other options)
```

**Comment by rederick29** [comment]
Deleting the metadata directory mentioned fixed the issue.
