### ISSUE TITLE
[BUG] Incorrect desktop link for 'Shadow Of The Tomb Raider'

### ISSUE THREAD

**Issue by djey47** [Dummerle/Rare#222]
**Describe the bug**
W10 - Only noticing this for the game SOTR so far, creating desktop link generates an empty dummy file which is not recognized as a valid shortcut.

**To Reproduce**
1. Go to 'Games' tab
2. Right Click on 'SOTR' game
3. Select 'Create Desktop link' menu entry
4. Watch the invalid shortcut created on the desktop

**Expected behavior**
A valid shortcut is present

**Screenshots**
![image](https://user-images.githubusercontent.com/2901949/175810170-9dd1838f-5bc1-464c-bfaf-6334a284a68e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2
- Installation MSI
- Python version  : Rare 1.8.9 embedded

**Additional context**
Workaround: by duplicating working shortcut (e.g GTAV here) and changing label, game ID + icon, it works fine.

**Error message**
https://gist.github.com/djey47/977f817b082d8ca6dc1919ab7f53fd05

**Comment by Dummerle** [comment]
I can reproduce the bug on the release. The bug is already fixed on a newer version, which is not in the stable release. A new release will be published soon

**Comment by djey47** [comment]
Great wok anyway, will test new release when it's out. Thanks !

**Comment by djey47** [comment]
Bug fixed on the latest release as announced. Thanks!
