### ISSUE TITLE
[BUG] Game not showning after downloading

### ISSUE THREAD

**Issue by thegame4craft** [Dummerle/Rare#227]
**Describe the bug**
After i downloaded the game `Cities: Skylines` last thursday using the download only button it isn't shown up in the installed list. 

**To Reproduce**
1. Buy game `Cities: Skylines`
2. Click on the game
3. Click on `Install Game`
4. Check in the popup the checkmark `Download Only`
5. Click on `Install` and wait until it is installed.
6. You can start the game using the file explorer but not using rare because rare marks it as uninstalled

**Expected behavior**

**Screenshots**
![grafik](https://user-images.githubusercontent.com/48205247/178141500-d6ff0744-b565-428a-b578-b5c36380efdd.png)
![grafik](https://user-images.githubusercontent.com/48205247/178141513-98b5ce23-f08f-4960-af51-08ce0968257e.png)
![grafik](https://user-images.githubusercontent.com/48205247/178141679-dd0edb02-7469-4dfd-8d86-3182201bf18f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21h2 Build 19044.1766
 - Rare Version 1.8.9
 - Installation using pip
 - Python 3.9.6

**Error message**
You can find error message in ~/.cache/rare/logs/
*Nothing found*

**Comment by Dummerle** [comment]
The download only option does not install the game. It won't appear in your library. You can import the game with the import game button

**Comment by thegame4craft** [comment]
Found how to import game

**Comment by loathingKernel** [comment]
We can improve the message a little, something like `The game won't appear as installed in your library`. Also, in what case does that option make sense in the context of Rare?
