### ISSUE TITLE
[BUG] Rare Flatpak does not start

### ISSUE THREAD

**Issue by dtantono** [Dummerle/Rare#246]
**Describe the bug**

**To Reproduce**
1. type flatpak run io.github.dummerle.rare on terminal

Traceback (most recent call last):
  File "/app/bin/rare", line 8, in <module>
    sys.exit(main())
  File "/app/lib/python3.9/site-packages/rare/__main__.py", line 104, in main
    from rare.app import start
  File "/app/lib/python3.9/site-packages/rare/app.py", line 15, in <module>
    from rare.components.dialogs.launch_dialog import LaunchDialog
  File "/app/lib/python3.9/site-packages/rare/components/dialogs/launch_dialog.py", line 7, in <module>
    from legendary.models.game import Game
ModuleNotFoundError: No module named 'legendary'

**Expected behavior**
it should run 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version 1.8.9
- Installation Flatpak
- Python version

**Additional context**

**Error message**
You can find error message in ~/.cache/rare/logs/

**Comment by Dummerle** [comment]
I see the build bot failed with the latest version. I had pushed the update for 1.9 before, but forgot to add legendary as dependency. I will push a fix later. It may take a while, before it gets published

**Comment by Dummerle** [comment]
Does it start now?

**Comment by dtantono** [comment]
Hi,
it works now. Thanks
