### ISSUE TITLE
[BUG] Failed to move game in Windows

### ISSUE THREAD

**Issue by Small-Ku** [Dummerle/Rare#248]
**Describe the bug**
is_mount method is not implemented on Windows.

**To Reproduce**
1. Go to a game
2. Click 'Move Installation'
3. Click 'Move'

**Expected behavior**
Move the game successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/16464896/192215216-73a94653-0313-4469-8916-f29e1e67ae4c.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.9.0
- Installation: scoop
- Python version:

**Additional context**

**Error message**
```
[Rare] CRITICAL: Traceback (most recent call last):
  File "D:\a\Rare\Rare\rare\components\tabs\games\game_info\game_info.py", line 261, in move_game
  File "D:\a\Rare\Rare\rare\components\tabs\games\game_info\move_game.py", line 70, in find_mount
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\pathlib.py", line 1593, in is_mount
NotImplementedError: Path.is_mount() is unsupported on this system
```

**Comment by StRonKEA** [comment]
verified. I encountered the same error.

**Comment by Dummerle** [comment]
Okay, thanks for reporting. I will check, how to fix this bug. It looks like a windows specific error.

If you have legendary installed you can run `legendary move <appname> C:\destination\path` in CMD.

**Comment by StRonKEA** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/9093980/192404017-27fa1a7c-0446-4fe1-a0b4-82821e77900f.PNG)
I have tested. moved the game to the directory I wanted, works fine

**Comment by loathingKernel** [comment]
The way Rare moves games is very different from legendary's. Cross-testing doesn't apply in this case.

**Comment by Dummerle** [comment]
I hope it works now? Then the issue can be closed

**Comment by Small-Ku** [comment]
It works fine. Thank you!
