### ISSUE TITLE
[BUG] 1.9.1 version not displayed

### ISSUE THREAD

**Issue by djey47** [Dummerle/Rare#250]
**Describe the bug**
Running latest windows 1.9.1 release still has 1.9.0 version info and warns about available update.

**To Reproduce**
1. Unzip 1.9.1 package
2. Run rare.exe
3. Go to Settings, About tab (!)
4. See Version still 1.9.0, update available 1.9.0 -> 1.9.1

**Expected behavior**
1.9.1 version is displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/2901949/193472830-dc6c0ede-7029-4687-a0cf-17fcc0e50cca.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.9.1
- Installation zip extract
- Python version embedded

**Additional context**
/

**Error message**
/

**Comment by StRonKEA** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/9093980/193473251-abfaa30e-ac0e-4efc-880d-544cfd98b5e6.PNG)
Are you sure you have installed version 1.9.1?

You can update from this link
https://github.com/Dummerle/Rare/releases/tag/1.9.1

**Comment by djey47** [comment]
Weird... I downloaded it again tonight and this time the version is okay.

Zip I got last week seems to have an issue....
