### ISSUE TITLE
[BUG] Windows bin file are not release with right filename

### ISSUE THREAD

**Issue by kxxoling** [Dummerle/Rare#253]
**Describe the bug**

There should be 1.9.1.msi along with 1.9.1.pkg

And this also breaks winget installation. I don't know how winget structures its apps db, but it trys to download from `https://github.com/Dummerle/Rare/releases/download/1.9.1/Rare-Windows-1.9.1.msi` as expected which got a 404 response of course.

**Screenshots**
![image](https://user-images.githubusercontent.com/1227139/197407203-4051b910-3a7b-4688-87f2-2d31e428b075.png)

**Comment by Dummerle** [comment]
I updated the name of the file. You can try it again

**Comment by kxxoling** [comment]
@Dummerle Downloading is successfully, but WinGet warned me a hash mismatch error, which I ignored, because I trust my environment and network. I'm not sure how it happens.

During the installation part, I encountered a singnature error. does that mean the `.msi` file needs to be signed?

**Comment by kxxoling** [comment]
I've checked SHA256 of the downloaded `.msi` executable on my Mac, find it is not matching the [winget-pkg config](https://github.com/microsoft/winget-pkgs/blob/master/manifests/d/Dummerle/Rare/1.9.1/Dummerle.Rare.installer.yaml):

```sh
❯ shasum -a 256 Rare-Windows-1.9.1.msi
d88a986a0ba0f68afd8d16aedccfbc5773678be316ffdea9cc99abbc874bb409  Rare-Windows-1.9.1.msi
```

**Comment by kxxoling** [comment]
Maybe it's better to add an CI job to contribute to [winget-pkgs](https://github.com/microsoft/winget-pkgs) is a better solution.

**Comment by kxxoling** [comment]
I found WinGet bot did update the hash of Rare installer manifest, it looks good now: https://github.com/microsoft/winget-pkgs/pull/86113

**Comment by kxxoling** [comment]
I found this seems to be useful: https://github.com/marketplace/actions/winget-releaser . Just FYI.
