### ISSUE TITLE
[BUG] Unable to start Fall Guys game

### ISSUE THREAD

**Issue by djey47** [Dummerle/Rare#263]
**Describe the bug**
Fall Guys game does not start from tile or desktop shortcut.

**To Reproduce**
1. Acquire and install Fall Guys game
2. Click on game tile to launch
3. Nothing happens 

**Expected behavior**
Game properly starts

**Desktop (please complete the following information):**
 - OS: W10
 - Version 1.9.4
 - Installation  MSI
- Python version: embedded

**Additional context**
Rare does not seem to launch correct game executable (or is this Legendary issue ?). There are at least 5 exe candidates (tested direct launch via Explorer, some work, some others don't). 
Also, it needs to be pointed out that directly launching game with correct executable - but without Epic launcher - leads to error before main menu; looks like Epic Games launcher has to share akind of token with the game. And neither Rare or Legendary seem to support this.

**Error message**
None

**Comment by Dummerle** [comment]
There are some debug options available. You can enable game debug console in rare settings. It will show a window with the output of the game, maybe it shows an error. Or you can launch Fall Guys via legendary, then we know, if it is an error on legendary side or on our side. For that you can run `legendary launch 0a2d9f6403244d12969e11da6713137b`

**Comment by djey47** [comment]
Legendary alone is able to launch the game without issues.

Also, after enabling the game console, and launching via Rare, messages don't appear in it. 
Besides, the game is then flagged as running and only the state is only restored after a legendary/epic succesfull launch, then exit.

**Comment by djey47** [comment]
![image](https://user-images.githubusercontent.com/2901949/211066046-aeac7749-0915-41fe-8671-e0b63dc768c0.png)

**Comment by djey47** [comment]
Latest build fixes starting of FG game. Thanks a lot!

**Comment by techgamers2** [comment]
getting this error now ( tried verifying / reinstalling / installing ESO also nothing worked )
![fallguys(error)](https://github.com/Dummerle/Rare/assets/44696073/de132f0d-9753-4eed-859a-27170c52db2b)
logs attached : 
[Rare_Launcher_0a2d9f6403244d12969e11da6713137b_23-05-20--19-22.log](https://github.com/Dummerle/Rare/files/11522480/Rare_Launcher_0a2d9f6403244d12969e11da6713137b_23-05-20--19-22.log)
