### ISSUE TITLE
[BUG] "No such file or direcotry" when starting GTAV

### ISSUE THREAD

**Issue by Rushmore75** [Dummerle/Rare#265]
**Describe the bug**
```bash
[GameUtils] ERROR: Error in game Grand Theft Auto V: execve: No such file or directory
[GameUtils] INFO: Game exited with exit code: 1
```
Trying to start GTAV but getting this error, I've verified the files and it checked out fine. The download was stopped and started during it but anything that errored there should have been caught with the verify, right?

**To Reproduce**
Download and try to start GTAV to custom directory

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 6.1.7-arch1-1
- Installation AUR (rare 1.9.5-1)
- Python version: 3.10.9

**Comment by Dummerle** [comment]
Do you have any wrappers configured, or exe override? 

Can you check `~/.config/legendary/installed.json` for `executable` and if it exists?

**Comment by Rushmore75** [comment]
it has `"install_path": "/home/oliver/drive/Games/GTAV",` as the path, so it should be fine. No wrappers or exe override (unless there are defualt ones)

**Comment by Dummerle** [comment]
Then the problem could be in wine. Do you have wine installed or do you use Proton? Maybe you have to set wine executable manually.

**Comment by Rushmore75** [comment]
I think I forget wine entirely lol, I though it would pull for aur as a dependency for rare (which I now see is an *optional* dependency, which I completely overlooked lol)
