### ISSUE TITLE
[BUG] Rare freezing while start (after login)

### ISSUE THREAD

**Issue by lennartbrandin** [Dummerle/Rare#268]
**Describe the bug**
When trying to start rare the Window opens and instantly becomes unresponsive.

**To Reproduce**
```bash
git clone https://github.com/Dummerle/Rare && cd Rare/
python -m rare --debug
```

**Expected behavior**
Rare logs in and opens the main window.

**Output**
```
[lennart@lennart-arch Rare]$ python3 -m rare --debug
/home/lennart/.local/lib/python3.10/site-packages/webview/platforms/gtk.py:34: PyGIWarning: Soup was imported without specifying a version first. Use gi.require_version('Soup', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Soup
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
[RareApp] INFO: Launching Rare version 1.9.5 Codename: Magnolia Catnip
 - Using Legendary 0.20.32 Codename: Dark Energy (hotfix #6) as backend
 - Operating System: Linux, Python version: 3.10.9
 - Running /usr/bin/python3 /home/lennart/Rare/rare/__main__.py --debug
 - Qt version: 5.15.8, PyQt version: 5.15.9
[Core] DEBUG: Set locale to en-US
[LGDLFS] DEBUG: Failed to load overlay install data: FileNotFoundError(2, 'No such file or directory')
[Core] INFO: Trying to re-use existing login session...
[LaunchDialog] INFO: You are logged in
[LGDLFS] DEBUG: Generating list of aliases...
```

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Version 1.9.5
- Installation source
- Python version 3.10.9

**Comment by loathingKernel** [comment]
Is this a first time running Rare and is Divine Knockout in your library?

**Comment by lennartbrandin** [comment]
I have run rare before so login and other saved data exists, im running it from source.
Im not sure if Divine Knockout is in my library as epic games marks it as "unavailable"
![image](https://user-images.githubusercontent.com/92579517/224511394-40d47a4e-15ff-4772-b5a4-4a08d36d5763.png)

**Comment by lennartbrandin** [comment]
It appears that Divine Knockout was once freely given away by epic games, so there is a high probability it is in my library.

**Comment by lennartbrandin** [comment]
Issue was in python depencies, fixed by using a virtualenv.
