### ISSUE TITLE
Feature Request: Minimized in taskbar

### ISSUE THREAD

**Issue by siltentassasin** [Dummerle/Rare#27]
I think it would be a nice feature if rare could be minimized in the taskbar, so that it can download/update games in the background an don't needed to stay open

It could be also helpful if it can started directly minimized e.g. with rare -silent, because so its possible to configure it in autostart

**Comment by Dummerle** [comment]
You can minimize it to system tray icon. In settings you can set the option. A --silent option should be no problem. Maybe I can add an option for auto updates, if it is in autostart
