### ISSUE TITLE
[BUG] Garlic Crab Release - Rare-Windows-1.10.0.zip is missing required files

### ISSUE THREAD

**Issue by MikeMaximus** [Dummerle/Rare#279]
**Describe the bug**
 Rare-Windows-1.10.0.zip is missing required files and the app will not start.

**To Reproduce**
Download Rare-Windows-1.10.0.zip and run rare.exe.

**Expected behavior**
The app should start.

**Screenshots**

![image](https://user-images.githubusercontent.com/15719732/235488379-07ea50b1-5eeb-49ca-864f-badf70070eaf.png)

**Desktop**
- OS: Windows 10
- Version: 1.10.0 
- Installation: Zip

**Additional context**
I tried the MSI installer with this release and it's fine.

**Error message**
See Screenshot.

**Comment by Dummerle** [comment]
The zip file wasn't generated correctly. I uploaded a new version of the file

**Comment by MikeMaximus** [comment]
The new zip seems to contain 1.9.4 instead of 1.10.0.

**Comment by Dummerle** [comment]
Next try. It should work now

**Comment by MikeMaximus** [comment]
Thanks it's working now.
