### ISSUE TITLE
Windows size smaller

### ISSUE THREAD

**Issue by Marcel-73** [Dummerle/Rare#28]
Is it possible to make the min heigh of the windows smaller?

**Comment by Dummerle** [comment]
Of course. What should be the new size?

**Comment by Marcel-73** [comment]
I think 400px should also work

**Comment by Dummerle** [comment]
400px is too small. I changed default to 800 px. You can resize the window, if you want. Do you want to have an option, to save the size of the window?

**Comment by Marcel-73** [comment]
Save size would be nice, I meant with the 400px the min-heihg, because I cann't size the heigh much, so I meant the min-heigh of the window, the default 800px sounds good

**Comment by Dummerle** [comment]
It was a bug and I fixed it. The option to save the size is coming soon
