### ISSUE TITLE
[Feature Request] option to autoclose rare after launching game

### ISSUE THREAD

**Issue by techgamers2** [Dummerle/Rare#282]
**Is your feature request related to a problem? Please describe.**
whenever i boot a game launcher should close completely
**Describe the solution you'd like**
add a new option in behavior section to close rare completely after game launch 

**Describe alternatives you've considered**
this close launcher completely option is available in battle.net launcher and it works flawlessly 
![image](https://user-images.githubusercontent.com/44696073/236178194-b46b8c09-d2bf-49d4-9e2f-62acc983d865.png)

**Additional context**
this will also improve game performance a little bit

**Comment by loathingKernel** [comment]
You can launch the game and close Rare from the system tray.

**Comment by techgamers2** [comment]
yes i know tht i can do tht in epic games launcher also ( just it would be easier if it was automatic feature like in battle.net launcher  )

> You can launch the game and close Rare from the system tray.

**Comment by loathingKernel** [comment]
This will probably not become a feature because of technical requirements and things that are out of our control. We cannot guarantee that we won't stop some other actively working process due to a forgetful or careless user. Launching through a shortcut or with `Rare.exe launch <app_name>` won't launch Rare itself, it will only launch the application you specified, effectively doing the same thing.

The performance improvement is not going to even be measurable, unless you are in a very very very memory constraint environment. Rare doesn't do anything in the background unless it is instructed to, so there is not performance hit either.

**Comment by loathingKernel** [comment]
Thinking about this, when it gets implemented it should be on a per-game basis, probably without a global option. Epic, unlike Battle.net, offers some fast-to-boot, lightweight games that can be played while waiting. Exiting will make using Rare more cumbersome. Currently we cannot exit Rare if certain processes are running, for example a game being verified or being moved. We cannot stop those processes normally, and if we do by other means, we cannot guarantee consistency given the current Legendary API. So normal exiting procedure should still apply, refusing to exit if there are active or waiting workers.

**Comment by techgamers2** [comment]
i know rare doesnt do anything in background but 140mb usage is pretty much same as epic launcher . if automatically closing rare after game launch would be added then there will be a solid reason to switch to rare launcher. and i m not forgetful to close rare just i dont play only one game i boot up many games at different time everytime its not possible for me to close rare. some people hav 16 gb to 32 gb of ram but not everyone . so if its implemental then it would be very useful for low end gamers like me

**Comment by loathingKernel** [comment]
That's interesting. What features did you turn off?

**Comment by techgamers2** [comment]
autoupdate , auto sync , download notification and discord rpc and exit to system tray now its pretty lite (ty for creating this project ) <3
