### ISSUE TITLE
[BUG] Unable to create fortnite shortcut 

### ISSUE THREAD

**Issue by techgamers2** [Dummerle/Rare#283]
when i try to create shortcut it shows error

**To Reproduce**
1. Go to 'installed FORTNITE game'
2. Click on 'right click and create shortcut link'
3. See error

**Expected behavior**
cant create shortcut for fortnite

**Screenshots**
![error](https://user-images.githubusercontent.com/44696073/236148160-b6c27d74-0378-4569-b29d-4aa814fd0158.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.10.1
- Installation: msi
- Python version

**Additional context**
other game i can create shortcut just getting error in fortnite

**Error message**
You can find error message in ~/.cache/rare/logs/

**Comment by techgamers2** [comment]
workaround : manually create a shortcut icon in desktop and set its target location to " C:\Users\<username>\AppData\Local\Programs\Rare\Rare.exe launch Fortnite "

**Comment by loathingKernel** [comment]
On Windows 10, creating shortcuts works for me, when done from my local development environment.

I also tested the `.zip` and `.msi` packages, and both of these also work for me. Are there spaces in your username?

**Comment by loathingKernel** [comment]
Please post the execution log that contains the error, you can find it under `C:\Users\<username>\AppData\Local\Rare\Rare\cache\logs`

**Comment by techgamers2** [comment]
[Rare_23-05-04--19-35.log](https://github.com/Dummerle/Rare/files/11398295/Rare_23-05-04--19-35.log)

**Comment by loathingKernel** [comment]
Ok, I see what is going on, Epic is being Epic as usual. Usually games specify an attribute called `FolderName` which is compatible with the Windows filesystem in terms of the characters being used in it. We use that attribute to name the shortcut, to avoid having to filter/mangle shortcut names. Fortnite specifically doesn't provide this attribute, meaning we can't create the shortcut.

PS: Why is it almost always when something goes wrong, or doesn't follows what the other games are doing, it is related to Fortnite?
