### ISSUE TITLE
[BUG] Duplicate installation 

### ISSUE THREAD

**Issue by techgamers2** [Dummerle/Rare#297]
**Describe the bug**
every time new update comes installer create different entries in programs section

**To Reproduce**

1. Go to 'install version 1.10.2'
2. Click on 'new version 1.10.3 msi installer '
3. Scroll down to 'add or remove programs u will see 2 installation one of 1.10.2 and other 1.10.3.'

**Expected behavior**
duplicates entries in add or remove program section

**Screenshots**
![duplicate](https://github.com/Dummerle/Rare/assets/44696073/81fc27ed-e32e-4c52-8e25-5eb366776119)

**System information**

Please complete the following information
- Operating system: [Windows 10]
- Version [e.g. 1.10.3]
- Installation method [msi]

**Comment by Dummerle** [comment]
For the moment you have to uninstall it manually. But I think I found an option to update the package. It will come in the next release

**Comment by Dummerle** [comment]
I pushed a fix. Unfortunately, it won't work until the next but one update
