### ISSUE TITLE
Rare vs HGL

### ISSUE THREAD

**Issue by plata** [Dummerle/Rare#3]
What are the differences compared to https://github.com/flavioislima/HeroicGamesLauncher? Would it make sense to join forces?

**Comment by Dummerle** [comment]
I use PyQt as framework in Rare. HGL uses JavaScript with Electron. That are diffrent things. My advantage is, that I can use the Legendary API and i don't have to use commands like "legendary list-installed". He has more possibilities to design the app, but it needs more ressources. So I think it is not the best option to use electron and JS

**Comment by plata** [comment]
Understood.
