### ISSUE TITLE
[BUG] Rare doesn't start up

### ISSUE THREAD

**Issue by awoken6** [Dummerle/Rare#306]
**Describe the bug**

Just yesterday rare was running as usual, even installed a game on it and played, but later on the same day when i opened it again to play another game, i got this out of nowhere, i have no ideia what it means
i also tried reinstalling it after this happened with and without choco, didn't make a difference

**To Reproduce**

1- i honestly do not know how this came to be

**Expected behavior**

the program to open like usual

**Screenshots**

![image](https://github.com/Dummerle/Rare/assets/141879635/468f4b21-e3de-4835-aaa8-55f68afc8989)

**Comment by loathingKernel** [comment]
As a first step try reinstalling Rare. There is an important dll missing. Did you run some system cleaner or something?

**Comment by awoken6** [comment]
> As a first step try reinstalling Rare. There is an important dll missing. Did you run some system cleaner or something?

i tried reinstalling it with and without choco.
No, i didn't run any system cleaner, the most i did was install some steam games

**Comment by awoken6** [comment]
oh my god wait, you're a genious
i actually had to reinstall some dlls cause a steam game wasn't starting soo, like i always do, i used this aio vc++ pack https://github.com/abbodi1406/vcredist
and now rare opened again
hah, sorry for this, you did actually help me for remembering me, even if it was something as dumb as this
thankyou
