### ISSUE TITLE
[BUG] Rare launcher not starting

### ISSUE THREAD

**Issue by Smgit5** [Dummerle/Rare#311]
**Describe the bug**

After installing Rare-1.10.3.msi on Windows 10, it is showing error message when starting.

**To Reproduce**

1. Install Rare-1.10.3.msi
2.  Run Rare.exe

**Expected behavior**
When double clicking rare.exe, it should launch rare launcher.

**Screenshots**

![image](https://github.com/Dummerle/Rare/assets/94289238/541a4af6-ecf0-4058-8aaa-138365c7efd9)

**System information**

- Operating system: Windows 10 version 22H2
- Version: Rare-1.10.3.msi
- Installation method: .msi

**Additional context**

I want to say that, I have used rare in the past (almost 1 year ago) without any problem. Then I stopped gaming for sometime, so uninstalled rare. Then, for a reason, I also formatted and clean installed windows 10 in my laptop. Today I installed rare launcher again and faced tis issue.

**Comment by loathingKernel** [comment]
You are missing vc runtime 2015
