### ISSUE TITLE
Rare System Tray 

### ISSUE THREAD

**Issue by siltentassasin** [Dummerle/Rare#36]
If rare was launched and is minimized in a system tray, its not possible to open the window via launching rare.

I think it would be very helpful if the session can reopened also via the command, currently its only possible via the system tray

**Comment by Dummerle** [comment]
This is difficult or I did not find an option to do this. At the moment you can just open the window from tray icon

**Comment by Hoimar** [comment]
Another option could be to have a additional file similar to the lockfile that `rare/utils/singleton.py` creates, so the running rare instance can watch this file, and when a new instance is launched, it writes to the file to signal to the running instance that another instance was launched.

There are probably better ways using some kind of sockets (saw some programs on Linux do it this way) or network communication as you mentioned, but the above might be easier to set up.

**Comment by Dummerle** [comment]
I think create a file is a good solution

**Comment by Dummerle** [comment]
If you use the git version, you can test it. If you start rare and there is already an instance in tray icon, the inctance opens

**Comment by siltentassasin** [comment]
I will thx :)
