### ISSUE TITLE
Feature Request: Detailed View some Options direkt not in info

### ISSUE THREAD

**Issue by siltentassasin** [Dummerle/Rare#37]
Hey, I think it would be very nice, if in the detailed view some options not all in the info menu, i think it would be better if they would be then listed

Here:
![Screenshot_20210411_201030](https://user-images.githubusercontent.com/81620892/114316098-526c4800-9b02-11eb-93f7-0cc11e20736b.png)

It could be so instead of

[ Start ]
[ Info ]

=>

[ Start ]
[ Uninstall ]
[ Info ]
[ Settings ]

**Comment by Dummerle** [comment]
That should be possible

**Comment by Dummerle** [comment]
I tested it and I don't relly like the look of it. What do you think about a right click menu?

**Comment by siltentassasin** [comment]
yes, right click menu sounds a lot better :)

**Comment by Dummerle** [comment]
In the pull request i added a context menu
