### ISSUE TITLE
[Bug] After Click on Install the Window move

### ISSUE THREAD

**Issue by siltentassasin** [Dummerle/Rare#43]
This is no relay important bug, but I think it would good if its fixed:

If I click in the normal view (not detailed) on game that isn't installed, it opens the install dialog,
but then if I move the cursor, the window move with it until I click anywhere

**Comment by Dummerle** [comment]
Which os and on Linux which Desktop do you use?

**Comment by siltentassasin** [comment]
Manjaro KDE 64bit with Qt5 and Kernel 5.11

**Comment by Dummerle** [comment]
And do you have the same problem with other dialogs?

**Comment by siltentassasin** [comment]
Only with rare dialogs

**Comment by Dummerle** [comment]
All rare dialogs? Or just install dlg?

**Comment by siltentassasin** [comment]
just install and only in the normal view, in the advanced the problem isn't there

**Comment by Dummerle** [comment]
I think it is a problem with pyqt. I have no idea, what's the error

**Comment by siltentassasin** [comment]
ok
