### ISSUE TITLE
cant download games

### ISSUE THREAD

**Issue by 0xemo** [Dummerle/Rare#46]
after hitting install ...games wont download .....

**Comment by Dummerle** [comment]
Please add more information. There is an issue template

**Comment by 0xemo** [comment]
okay so im using it on windows. no error when launching.. everything fine...but when i try to download game...download progress appear stuck and no network utilization in task manager
![Capture](https://user-images.githubusercontent.com/82674836/115072698-74f0cd80-9f15-11eb-987e-79a1b505b6f8.PNG)

**Comment by 0xemo** [comment]
![Screenshot (77)](https://user-images.githubusercontent.com/82674836/115073587-2b54b280-9f16-11eb-9f0a-44e4abf2bf7a.png)

**Comment by Dummerle** [comment]
Which version of rare do you use? .exe or pip

**Comment by Dummerle** [comment]
And were there the popups for download settings and download size?

**Comment by ChemicalXandco** [comment]
Does it work when you try to install other games e.g. rocket league?

**Comment by 0xemo** [comment]
im using .exe version....and yes popups appears but no download progress after hitting install ......it doesnt work i tried to install gtav abzu.

**Comment by Dummerle** [comment]
Try the latest release. And if it does not work, send me the latest logfile from <home>/.cache/rare/logs/

**Comment by 0xemo** [comment]
[log.zip](https://github.com/Dummerle/Rare/files/6329382/log.zip)

**Comment by Dummerle** [comment]
Its empty

**Comment by 0xemo** [comment]
![Screenshot (81)](https://user-images.githubusercontent.com/82674836/115117313-7f65a280-9fbb-11eb-99ef-b5c8194aa5b3.png)

**Comment by Dummerle** [comment]
I tested it on my Windows VM and i got the same error. Maybe it is the Defender or other anti virus. When i install it with pip, it works. 

The problem is, every pc reacts diffrent to the exe file. A friend had a problem, that the app got killed after 5 seconds. We can't download games.

**Comment by 0xemo** [comment]
okay then ill try pip version...btw thanks for support

**Comment by Dummerle** [comment]
No problem

**Comment by 0xemo** [comment]
dude.....pip version running fine....tysm dude
