### ISSUE TITLE
Feature Request: Free Games auto show/add

### ISSUE THREAD

**Issue by siltentassasin** [Dummerle/Rare#49]
Is it possible to add a option that displays the free game of the week in rare or maybe its possible to add a option in the settings to activate that this games will auto added to the acc?

I think this would be very nice

**Comment by Dummerle** [comment]
Display the free game is possible and I want to add it with version 2.0 with some other games from epic page. 

I have no option to buy the game. You have to do this in store. Maybe it is possible with selenium, but that could cause too many errors and it would work on some devices

**Comment by mobilegmYT** [comment]
> Display the free game is possible and I want to add it with version 2.0 with some other games from epic page.
> 
> I have no option to buy the game. You have to do this in store. Maybe it is possible with selenium, but that could cause too many errors and it would work only on few devices

It is possible with selenium as seen here: https://github.com/MasonStooksbury/Free-Games. It's firefox only so tweaking is needed for chrome support.

**Comment by Dummerle** [comment]
I took a look at it and it looks too difficult to setup. I will search for a better solution

**Comment by mobilegmYT** [comment]
https://pypi.org/project/epic-games-bot/ also seems to be a good one too.

**Comment by Dummerle** [comment]
I think i will add some features with https://github.com/SD4RK/epicstore_api and add a link to free game etc. Auto add games, is very difficult with authentication and right dependencies like selenium and the right webdriver.

**Comment by mobilegmYT** [comment]
> I think i will add some features with https://github.com/SD4RK/epicstore_api and add a link to free game etc. Auto add games, is very difficult with authentication and right dependencies like selenium and the right webdriver.

True. Maybe for the store button and also for auto add game you could make it open the pages in a embed so it's more self contained.

**Comment by Dummerle** [comment]
For an embed i need pyqtwebengine as dependency and in a very early version it was in the code. But it caused many errors, was a big part of application size and wasn't really needed. You can check it in `old` branch

**Comment by Dummerle** [comment]
Maybe I will a clone of the website with link to free game and some other games from API

**Comment by Dummerle** [comment]
Shop actions require a captcha, so it is impossible to auto add free games

**Comment by mobilegmYT** [comment]
> Shop actions require a captcha, so it is impossible to auto add free games

Would it be possible to make the user do the capcha but automate everything else with something like selenium?

**Comment by loathingKernel** [comment]
It is unclear but in any case it is outside the scope of Rare in my opinion. Too much effort for very marginal gains.

**Comment by Dummerle** [comment]
We could add a notification, if a new free game is available. But we don't need an extra large dependency like selenium

**Comment by loathingKernel** [comment]
The shop doesn't load at startup though for performance reasons. Do you think it would be easy to add something similar to the downloads tab number of updates without loading the whole shop? Other potential solution would be a tray notification, a status bar persistent message, or a small banner in the games library.

**Comment by Dummerle** [comment]
> Do you think it would be easy to add something similar to the downloads tab number of updates without loading the whole shop

Checking for free games is just a simple request

All of the notification options are possible
