### ISSUE TITLE
Feature Request: Game Image Color by downloading

### ISSUE THREAD

**Issue by siltentassasin** [Dummerle/Rare#50]
Can you make that the image of a game will colored more by downloading, 

e.g.

1% = 1% colored
47% = 47 colored
...

**Comment by Dummerle** [comment]
Nice idea, but I think it is very difficult. 

Maybe I add label to show progress and show it at first place

**Comment by MultisampledNight** [comment]
Just a few ideas, I am just assuming things about the codebase I don't know about.
The idea is to first draw a greyscaled version of the image in "full" scaled size, and then draw over that a cropped version of the actual image.
The creation of a greyscaled image could probably be done using [QPixmap.convertFromImage](https://www.riverbankcomputing.com/static/Docs/PyQt5/api/qtgui/qpixmap.html#convertFromImage) and the `MonoOnly` variant of [ImageConversionFlag](https://www.riverbankcomputing.com/static/Docs/PyQt5/api/qtcore/qt.html#ImageConversionFlag-AutoColor).
Cropping could be done using a `QRect` and then using the `copy` method on the actual QImage.

However, this would probably need some changes. Currently, the actual drawing of the "uninstalled" image and the layouting seems to be seperated into `rare/components/tabs/games/game_widgets/base_uninstalled_widget.py` and `rare/components/tabs/games/game_widgets/uninstalled_icon_widget.py`. The first one handles the actual image drawing, but only the second one seems to know about if a game is currently installing or not. I'd say the widget for an "installation" deserves it's own widget class, like `installing_icon_widget.py`.

(By the way, take your time. No need to haste.)

**Comment by Dummerle** [comment]
Done
