### ISSUE TITLE
[Feature Request] Logs 

### ISSUE THREAD

**Issue by siltentassasin** [Dummerle/Rare#51]
Can you make in the settings of a game a link to the game logs?

**Comment by Dummerle** [comment]
Do you mean a link to open explorer?

**Comment by siltentassasin** [comment]
yes sth like that, to easily just click somewhere and get direct to the logs

**Comment by Dummerle** [comment]
I have a lot to do at the moment. I will add it in a couple of days

**Comment by Dummerle** [comment]
A button is added in settings
