### ISSUE TITLE
show playing game name only on discord

### ISSUE THREAD

**Issue by adrianmak** [Dummerle/Rare#54]
Currently, it will show" playing a game rare xxxxxxxxx via Rare on Windows"
Could u please add an option to toggle show playing xxxxxxxxx  on discord only

**Comment by MultisampledNight** [comment]
There is already. In the settings are these checkboxes:

![image](https://user-images.githubusercontent.com/80128916/116507838-61077d00-a8c0-11eb-8b38-736ce9d47ac4.png)

So in your case, you'd have to disable `Show OS`, `Show Time playing` and only enable `Show Game`.
