### ISSUE TITLE
[Feature Request] Add installed games in the menu

### ISSUE THREAD

**Issue by siltentassasin** [Dummerle/Rare#56]
Can you create for installed games a menu entry? And remove them by uninstallation? 

Because then its possible to pin games directly in the taskbar

**Comment by Dummerle** [comment]
You can create a Startmenu entry on Linux. When the game gets uninstalled i have to add a function to remove entry. 

Windows shortcuts are more difficult than on Linux. I don't know a good solution. There are pip packages and then i have to add them only for windows.
