### ISSUE TITLE
Add search filters

### ISSUE THREAD

**Issue by mobilegmYT** [Dummerle/Rare#58]
I think it would be nice to also have filters for what you are searching for. Like eg listing games which are 64-bit or 32-bit.

**Comment by Dummerle** [comment]
I don't know hot to get, if a game is 32 or 64 bit. Eg. Offline and Online should be possible

**Comment by Dummerle** [comment]
I added offline games filter. Platform looks difficult, so it will take a while

**Comment by Dummerle** [comment]
You can list 32 Bit games, but you can't install them.

**Comment by mobilegmYT** [comment]
> You can list 32 Bit games, but you can't install them.

Actually, you can. I've done it before. eg, Night In the Woods has both a 32-bit and 64-bit download hosted on Epic's servers. A command like `legendary download cd1b8a6e5b6c47369e2a1e2cf7b7f536 --platform Win32` will download the 32-bit version, and I've checked that the downloaded exe is 32-bit.

**Comment by Dummerle** [comment]
With `download` you just download the data. It does not install it

**Comment by mobilegmYT** [comment]
> With `download` you just download the data. It does not install it

It should work with install too.

**Comment by Dummerle** [comment]
> It should work with install too.

If you set platform, no-install is set too

**Comment by mobilegmYT** [comment]
> > It should work with install too.
> 
> If you set platform, no-install is set too

Ohhhh, well maybe you could also add a download feature alongside the install button?

**Comment by Dummerle** [comment]
Done. You find it in Install Dialog

**Comment by mobilegmYT** [comment]
Sweet!
