### ISSUE TITLE
rare python version on windows not launching.

### ISSUE THREAD

**Issue by 0xemo** [Dummerle/Rare#59]
rare version is 1.4.0 after opening, cmd open for 3 sec then close and nothing happens.

**Comment by Dummerle** [comment]
Is there output in cmd and which version of rare, do you use? Pip or msi?

**Comment by 0xemo** [comment]
no output and pip(python) version

**Comment by Dummerle** [comment]
I forgot `pywin32` in setup.py. You can install it manually with `pip install pywin32`

**Comment by 0xemo** [comment]
oh okay
