### ISSUE TITLE
Option to Turn off/Custom Wine usage in Rare??

### ISSUE THREAD

**Issue by Angell1993** [Dummerle/Rare#6]
I handle Wine/Proton myself, so it would be great if I can just install without using default wine.. If possible..

**Comment by Angell1993** [comment]
Custom Wine Launch script.. (If you wanted to make use of different wine versions beside default..)

mangohud /usr/bin/env WINE='<Wine Folder>/bin/wine'  WINEPREFIX='<Prefix path>' WINESERVER='<Wine Folder>/bin/wineserver'  WINELOADER='<Wine Folder>/bin/wine' WINEDLLPATH='<Wine Folder>/lib64' WINEARCH='win64' "<exe Path>"

mangohud == fps monitor.. (Can be removed if not wanted..)

App GOverlay, can be used to customize MangoHud..

I also got Custom Proton scripts, if you wanted that as well..

VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json == AMD Mesa driver with Vulkan.. (Can be changed to other versions installed or removed for default selection.)

PRESSURE_VESSEL_FILESYSTEMS_RO="$MANGOHUD_CONFIGFILE:$VKBASALT_CONFIG_FILE"  == MangoHud fps monitor.. (With Latest Proton.. Can be removed if not wanted..)

Exec=env VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json PRESSURE_VESSEL_FILESYSTEMS_RO="$MANGOHUD_CONFIGFILE:$VKBASALT_CONFIG_FILE" STEAM_COMPAT_DATA_PATH="<Proton Prefix>" "<Steam Folder>/steamapps/common/Proton 5.13/proton" run "<exe Path>"

**Comment by Dummerle** [comment]
Yes I plan it, but for the moment you have to set it manually in the legendary config

**Comment by Angell1993** [comment]
I got an interesting question, is the games dependent on Legendary to work??

Seeing I got Proton to launch one of my games without the use of Legendary?? With quite the fps boost..

**Comment by Dummerle** [comment]
For some games you need to be logged in. That handles legendary. But many games have an offline option, so you can start them without legendary.

**Comment by Dummerle** [comment]
With the next release I add most settings from legendary

**Comment by Angell1993** [comment]
oki..
I think I got the custom wine to work properly with Legendary, so that shouldn't be too hard to use..
but it would be great to have the option to use proton too, but seeing that it's not really part of Legendary it might not work as intended..

**Comment by Dummerle** [comment]
I added many settings. Now you can set wrapper and no_wine
