### ISSUE TITLE
Styles is missing in Master Build??

### ISSUE THREAD

**Issue by Angell1993** [Dummerle/Rare#7]
Styles is missing in Master Build??
Is that on purpose??

Seeing it is asking for it..

**Comment by Dummerle** [comment]
Do you get an error?

**Comment by Angell1993** [comment]
[Terminal output]
running install
running bdist_egg
running egg_info
creating Rare.egg-info
writing Rare.egg-info/PKG-INFO
writing dependency_links to Rare.egg-info/dependency_links.txt
writing entry points to Rare.egg-info/entry_points.txt
writing requirements to Rare.egg-info/requires.txt
writing top-level names to Rare.egg-info/top_level.txt
writing manifest file 'Rare.egg-info/SOURCES.txt'
error: package directory 'Styles' does not exist

**Comment by Angell1993** [comment]
I can't tell what the difference is in the install part from the Release to the Master..
Hope you have some idea..

Seeing even if I looked at the code, I'm a C# developer not a Python developer..
Some syntax might be similar but it will be too different to do anything with it for me..

**Comment by Dummerle** [comment]
I fixed the setup.py file. It should work now. The Master is always up to date. The Releases are more stable and have less bugs
