### ISSUE TITLE
[Bug] Error when trying to install any game

### ISSUE THREAD

**Issue by Sm1leAway** [Dummerle/Rare#73]
OS: Windows
Install type: MSI installation
Version: Both 1.4.1 and 1.5beta2

When trying to install any game error attached pops up.
![rareerr](https://user-images.githubusercontent.com/34925689/120040399-c016f980-c006-11eb-86fc-97d07ec6bafa.png)

Pip on the other hand works perfectly fine, but pip version is still 1.2.1

**Comment by ChemicalXandco** [comment]
This is a known issue. Use the `pip` package until it is fixed. Use the command `pip install Rare --upgrade` to update it.

**Comment by Sm1leAway** [comment]
Will do, thanks for the command.
