### ISSUE TITLE
How can I use the Proton Wrapper for a specific game?

### ISSUE THREAD

**Issue by jamiefraser77** [Dummerle/Rare#76]
I'm trying to run Rocket League with Proton (installed to `/home/jam/.steam/compatibilitytools.d`)

However, in the RL settings, the Proton Wrapper drop down doesn't have the option to select a specific proton folder:

https://i.imgur.com/JhxMoKk.png

**Comment by Dummerle** [comment]
I pushed a commit that adds ~/.steam/compatibilitytools.d. If you install it from source, your proton version should be in the list

**Comment by jamiefraser77** [comment]
Thanks that worked :)

**Comment by loathingKernel** [comment]
I think that is not how it is supposed to be. Why is your `compatibilitytools.d` in `~./steam`? Did you put it there? The search paths for steam are these https://github.com/ValveSoftware/steam-for-linux/issues/6310#issuecomment-511630263

**Comment by jamiefraser77** [comment]
`compatibilitytools.d` is in `~./steam` because that is where a previous version of GE Proton recommended that it be installed to.

In the current version of his [readme](https://github.com/GloriousEggroll/proton-ge-custom#installation) it recommends: `~/.steam/root/compatibilitytools.d`
