### ISSUE TITLE
Game install/download issue

### ISSUE THREAD

**Issue by Angell1993** [Dummerle/Rare#8]
It's like it just steps over the entire install process, any idea why??
The game disappears in game Library, but reappears on relaunch like nothing happened..

I've tried to use default install location and custom, same issue..

Using Rare-Master..

Is there something I'm missing??

[Terminal output]
[Game] INFO: install Beyond Two Souls
{'install_path': '/run/media/angel/E/Games/legendary'}
[Game] INFO: install Lavender in path /run/media/angel/E/Games/legendary
[Game] INFO: Download finished

**Comment by Dummerle** [comment]
I think it is a bug. I take a look at it today or tomorrow

**Comment by Dummerle** [comment]
I fixed it. Now you can download and install Games, but you will only get a notification when download finished. I plan to implement a progressbar, but with legendary api is it very difficult, because it writes it only to stdout

**Comment by Angell1993** [comment]
oki..
