### ISSUE TITLE
String visualization issue

### ISSUE THREAD

**Issue by alsoGAMER** [Dummerle/Rare#81]
Some strings in rare and games settings aren't shown correctly
Version 1.4.1

![image](https://user-images.githubusercontent.com/35269770/121806510-63dfe680-cc50-11eb-9ebb-77241f560133.png)

**Comment by Dummerle** [comment]
You can try to use git version. There are some style changes. I will publish a release soon

**Comment by alsoGAMER** [comment]
The git version doesn't even start

Version: 1.5_beta2.r12.g0246b96-1

Traceback (most recent call last):
```
  File "/usr/bin/rare", line 33, in <module>
    sys.exit(load_entry_point('Rare==1.4.1', 'console_scripts', 'rare')())
  File "/usr/lib/python3.9/site-packages/rare/__main__.py", line 62, in main
    start(args)
  File "/usr/lib/python3.9/site-packages/rare/app.py", line 127, in start
    app = App(args)
  File "/usr/lib/python3.9/site-packages/rare/app.py", line 95, in __init__
    if self.launch_dialog.offline:
AttributeError: 'LaunchDialog' object has no attribute 'offline
```

**Comment by Dummerle** [comment]
It should be fixed

**Comment by alsoGAMER** [comment]
> It should be fixed

Yep, now it startups fine, and all the strings and menus are displayed properly.
Thanks for your work, keep it up ^^
