### ISSUE TITLE
Where is the config file?

### ISSUE THREAD

**Issue by MrSwedish** [Dummerle/Rare#82]
it crashes, and here is the short console log:
```
Traceback (most recent call last):
  File "/usr/bin/rare", line 33, in <module>
    sys.exit(load_entry_point('Rare==1.4.1', 'console_scripts', 'rare')())
  File "/usr/lib/python3.9/site-packages/rare/__main__.py", line 62, in main
    start(args)
  File "/usr/lib/python3.9/site-packages/rare/app.py", line 127, in start
    app = App(args)
  File "/usr/lib/python3.9/site-packages/rare/app.py", line 52, in __init__
    if self.core.egl_sync_enabled and not os.path.exists(self.core.egl.programdata_path):
  File "/usr/lib/python3.9/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

seems to be egl or something, I would like to reset it
(Arch linux and git version btw)

**Comment by loathingKernel** [comment]
The affected config is legendary's and it is in `~/.config/legendary/config.ini`, you have to remove the `egl_programdata` config option. If you could, please check if it is present and empty (i.e. without specifing a path) as I have encountered that error and want to know if it is the same problem. If it is, we have a fix in the queue already.

**Comment by MrSwedish** [comment]
sounds good, thanks

**Comment by MrSwedish** [comment]
i had to remove `egl_sync = true`
instead of `egl_programdata `

**Comment by loathingKernel** [comment]
These two settings interact with each other. Did you try to remove `egl_programdata` and it didn't work or it wasn't there in the first place?

**Comment by MrSwedish** [comment]
it was there but removing it didn't do the difference, i could start it even when it was still there

**Comment by loathingKernel** [comment]
Ok, thank you for the information.

**Comment by MrSwedish** [comment]
no problem

**Comment by MrSwedish** [comment]
is dxvk built in, if yes how do i change it?
(sorry for the off-topic question)

**Comment by loathingKernel** [comment]
Rare doesn't manage the wine prefix you are going to use to run games, such as installing dxvk etc, you have to do it on your own. On the other hand, you can use Rare to modify what dxvk will display either through the global settings or in a per-game basis by clicking the gear icon in an installed game.

**Comment by MrSwedish** [comment]
thanks again!
