### ISSUE TITLE
Settings are too close to read

### ISSUE THREAD

**Issue by SharkLava** [Dummerle/Rare#84]
![image](https://user-images.githubusercontent.com/28181349/122142059-3ec7bf80-ce6c-11eb-845b-723de3bd6514.png)
The settings text is too close together so i cant read any of them.

OS:Manjaro Linux

**Comment by Dummerle** [comment]
You can use git version.  In the next days I will publish a new release

#81

**Comment by MrSwedish** [comment]
that didn't happen to me

**Comment by SharkLava** [comment]
Oh alright. Thank you!
