### ISSUE TITLE
Linux Install as user instead of root

### ISSUE THREAD

**Issue by Angell1993** [Dummerle/Rare#9]
I'm wondering why you inform people to install with root instead of user..

[Install as user..]
python3 setup.py install --user

[Install as root/admin..]
python3 setup.py install

Does it make a difference??

**Comment by Dummerle** [comment]
I added the user option

**Comment by Angell1993** [comment]
I've only tested the --user option with the manual install, I don't know if it work with pip though.. Just thought you should know..
