### ISSUE TITLE
AppImage.

### ISSUE THREAD

**Issue by kajlamo** [Dummerle/Rare#90]
Would it be possible to add AppImage support?

**Comment by Dummerle** [comment]
Sure, but I am not at home and I don't experience with appimages

**Comment by kajlando** [comment]
https://github.com/AppImage/pkg2appimage
https://github.com/simoniz0r/deb2appimage

**Comment by kajlando** [comment]
https://github.com/AppImage/pkg2appimage

**Comment by Dummerle** [comment]
I am not at home so I can't add it. I will check it out, when I am at home

**Comment by poVoq** [comment]
Should be fairly simple with this: https://github.com/probonopd/linuxdeployqt

**Comment by Dummerle** [comment]
I will check it out

**Comment by Dummerle** [comment]
With the next release, an AppImage is generated!

**Comment by kajlamo** [comment]
Thank you.
