### ISSUE TITLE
App Crash when looking through individual game settings

### ISSUE THREAD

**Issue by Angell1993** [Dummerle/Rare#94]
[Error]
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/rare/components/tabs/games/game_info/game_settings.py", line 34, in <lambda>
    self.offline.currentIndexChanged.connect(lambda x: self.update_combobox(x, "offline"))
  File "/usr/lib/python3.9/site-packages/rare/components/tabs/games/game_info/game_settings.py", line 122, in update_combobox
    self.core.lgd.config.add_section(self.game.app_name)
  File "/usr/lib/python3.9/configparser.py", line 1211, in add_section
    super().add_section(section)
  File "/usr/lib/python3.9/configparser.py", line 659, in add_section
    raise DuplicateSectionError(section)
configparser.DuplicateSectionError: Section 'Lavender' already exists
Aborted (core dumped)

Does anyone know why this is happening when browsing individual game settings??

**Comment by Angell1993** [comment]
Rare: v1.4.1
OS: Manjaro 21.1.0 Pahvo
Kernel: x86_64 Linux 5.13.8-1-MANJARO
Shell: bash 5.1.8
WM: OpenBox
CPU: AMD Ryzen 7 3800X 8-Core @ 16x 4GHz
GPU: AMD Radeon RX 6800 XT (SIENNA_CICHLID, DRM 3.41.0, 5.13.8-1-MANJARO, LLVM 12.0.1)

**Comment by Angell1993** [comment]
After closer inspection, it looks like to be triggered when the mouse is hovering over elements on the individual game settings..

**Comment by Dummerle** [comment]
With the new release, it will be fixed. You can use git version

**Comment by Dummerle** [comment]
Does it work?

**Comment by Angell1993** [comment]
In the Git Version, I didn't have the issue, so no crash so far, I've not been able to recreate the problem..
