### ISSUE TITLE
Looks for python in hardcoded user directory

### ISSUE THREAD

**Issue by bitcoin-roomba** [Dummerle/Rare#96]
![image](https://user-images.githubusercontent.com/40922598/130144382-cc9d3751-2ed5-4e08-83cd-6a435d8b5c92.png)

Someone's user directory path is hardcoded in. There is no user named "lenna" on my PC.

**Comment by Dummerle** [comment]
Deploy python applications on windows is very hard. I will check another option to create exe files. You can use pip version as described in README.md

**Comment by Dummerle** [comment]
Does it work with the file from version 1.4.1?

**Comment by bitcoin-roomba** [comment]
Yeah, 1.4.1 is the latest version I have installed, it works.

**Comment by Dummerle** [comment]
Thats weird. It was the same script

**Comment by Dummerle** [comment]
I will upload a new msi file
