### ISSUE TITLE
Pip version on Windows: python cannot find module unless module-info directory is renamed.

### ISSUE THREAD

**Issue by bitcoin-roomba** [Dummerle/Rare#97]
After installing Rare through pip on Windows, python can't find a module named Rare when running `python -m Rare`. Workaround: go to %LOCALAPPDATA%\Programs\Python\Python39\Lib\site-packages , rename the "Rare-1.5.0.dist-info" directory to "rare-1.5.0.dist-info" (lowercase first letter), and run `python -m rare` (with lowercase r).

**Comment by bitcoin-roomba** [comment]
For some reason on Windows pip creates the rare install directory with a lowercase r and the module-info directory with an uppercase R. Renaming the rare install directory to uppercase throws errors due to python being unable to find the rare module while running the scripts, as all instances of "rare" in the source code are lowercase.

**Comment by MultisampledNight** [comment]
The commad is `pythonw -m rare`, as listed in the README.md. Did you try that first before renaming the package folder? The capitalization of the package folder shouldn't matter on Windows; NTFS, the filesystem Windows runs on, is case-insensitive. That means, no matter if you open `foobar.txt`, `FooBAr.txt` or `FOOBAR.TXT`, they'll all show the same file.

**Comment by bitcoin-roomba** [comment]
I misread the launch command, it works if you don't capitalize like I did. I was wondering why it would make a difference at all since windows paths are, as you said, case-insensitive.  I retract the issue.
